### ISSUE TITLE
Tests fail with postgresql

### ISSUE THREAD

**Issue by jmound** [django-oscar/django-oscar-api#18]
The oscarapi tests pass  with sqlite as a db backend, and fail when run with postgres:

```
$ virtualenv env
$ . env/bin/activate
(env)web@vagrant-ubuntu-trusty-64:~$ git clone git@github.com:django-oscar/django-oscar-api.git
(env)web@vagrant-ubuntu-trusty-64:~$ cd django-oscar-api/
(env)web@vagrant-ubuntu-trusty-64:~$ make test
...
Ran 43 tests in 10.923s

OK
```
- Swap out DATABASES in sandbox/settings.py with a postgresql configuration: ''ENGINE': 'django.db.backends.postgresql_psycopg2',' along with a working set of settings 
  - `pip install psycopg2`
- and re-run:

```
(env)web@vagrant-ubuntu-trusty-64:~$ make test
 ...
Ran 43 tests in 11.163s

FAILED (errors=3, failures=14)
```

The full output is pretty long. Here is one of the errors:

```
======================================================================
ERROR: A regular or anonymous user should not be able to fetch someone elses basket.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/web/django-oscar-api/oscarapi/tests/testbasket.py", line 169, in test_basket_read_permissions
    self.assertEqual(str(b.owner), 'nobody')
  File "/home/web/env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 572, in __get__
    rel_obj = qs.get()
  File "/home/web/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
DoesNotExist: User matching query does not exist.
```

**Comment by specialunderwear** [comment]
Most likely that is caused by the fixtures not loading properly.
Are you seeing any fixture loading errors?
