### ISSUE TITLE
Errors generating a schema

### ISSUE THREAD

**Issue by jayvdb** [django-oscar/django-oscar-api#214]
I have installed https://github.com/django-oscar/django-oscar-api/pull/213 , and tried the core DRF and numerous custom API generators (drf-yasg, drf-spectacular, etc) and they all have these errors, and many many more:

```py
view's PaymentStatesView raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/usr/local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'PaymentStatesView' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's LineList raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/shortcuts.py", line 93, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
oscar.apps.basket.models.Basket.DoesNotExist: Basket matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/usr/local/lib/python3.6/site-packages/oscarapi/views/basket.py", line 293, in get_queryset
    basket = self.check_basket_permission(self.request, basket_pk=basket_pk)
  File "/usr/local/lib/python3.6/site-packages/oscarapi/views/utils.py", line 54, in check_basket_permission
    basket = generics.get_object_or_404(Basket.objects, pk=basket_pk)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/shortcuts.py", line 95, in get_object_or_404
    raise Http404('No %s matches the given query.' % queryset.model._meta.object_name)
django.http.response.Http404: No Basket matches the given query.
view's LineList raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/shortcuts.py", line 93, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
oscar.apps.basket.models.Basket.DoesNotExist: Basket matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/usr/local/lib/python3.6/site-packages/oscarapi/views/basket.py", line 293, in get_queryset
    basket = self.check_basket_permission(self.request, basket_pk=basket_pk)
  File "/usr/local/lib/python3.6/site-packages/oscarapi/views/utils.py", line 54, in check_basket_permission
    basket = generics.get_object_or_404(Basket.objects, pk=basket_pk)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/shortcuts.py", line 95, in get_object_or_404
    raise Http404('No %s matches the given query.' % queryset.model._meta.object_name)
django.http.response.Http404: No Basket matches the given query.
view's BasketLineDetail raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/shortcuts.py", line 93, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
oscar.apps.basket.models.Basket.DoesNotExist: Basket matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/usr/local/lib/python3.6/site-packages/oscarapi/views/basket.py", line 325, in get_queryset
    basket = get_object_or_404(operations.editable_baskets(), pk=basket_pk)
  File "/usr/local/lib/python3.6/site-packages/django/shortcuts.py", line 95, in get_object_or_404
    raise Http404('No %s matches the given query.' % queryset.model._meta.object_name)
django.http.response.Http404: No Basket matches the given query.
view's BasketLineDetail raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/shortcuts.py", line 93, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
oscar.apps.basket.models.Basket.DoesNotExist: Basket matching query does not exist.
```

**Comment by jayvdb** [comment]
I have been able to get a schema generated by crafting hacks around two issues raised at https://github.com/tfranzel/drf-spectacular/issues/jayvdb

**Comment by jayvdb** [comment]
drf-spectacular `master` now works well, if https://github.com/django-oscar/django-oscar-api/pull/213 is used.

I get 100+ warnings related to oscar-api after that PR, but not many appear serious.

**Comment by maerteijn** [comment]
Will close as #213 is merged now.

**Comment by jayvdb** [comment]
Great.  drf-spectacular has a dedicated docs for this API
https://drf-spectacular.readthedocs.io/en/latest/blueprints.html#django-oscar-api
